<?php

namespace Zerotoprod\SpapiLwa\Support\Testing;

class SpapiLwaResponseFactory
{
    public static function refreshTokenOk(array $merge = []): array
    {
        return array_merge([
            "info" => [
                "url" => "https://api.amazon.com/auth/o2/token",
                "content_type" => "application/json;charset=UTF-8",
                "http_code" => 200,
                "header_size" => 485,
                "request_size" => 898,
                "filetime" => -1,
                "ssl_verify_result" => 0,
                "redirect_count" => 0,
                "total_time" => 0.359889,
                "namelookup_time" => 0.070204,
                "connect_time" => 0.150098,
                "pretransfer_time" => 0.235468,
                "size_upload" => 619,
                "size_download" => 763,
                "speed_download" => 2125,
                "speed_upload" => 1724,
                "download_content_length" => 763,
                "upload_content_length" => 619,
                "starttransfer_time" => 0.359795,
                "redirect_time" => 0,
                "redirect_url" => "",
                "primary_ip" => "98.82.156.189",
                "certinfo" => [],
                "primary_port" => 443,
                "local_ip" => "172.20.0.2",
                "local_port" => 56232,
            ],
            "error" => "",
            "headers" => [
                "Server" => "Server",
                "Date" => "Thu, 13 Feb 2025 19:37:11 GMT",
                "Content-Type" => "application/json;charset=UTF-8",
                "Content-Length" => "763",
                "Connection" => "keep-alive",
                "X-Amz-Rid" => "DCTFJ9AFPC1MM9Z605M2",
                "X-Amzn-Requestid" => "5cac54f3-9d1e-432f-a05a-a6c101b93eab",
                "X-Amz-Date" => "Thu, 13 Feb 2025 19:37:11 GMT",
                "Cache-Control" => "no-cache, no-store, must-revalidate",
                "Pragma" => "no-cache",
                "Vary" => "Content-Type,Accept-Encoding,User-Agent",
                "Strict-Transport-Security" => "max-age=47474747; includeSubDomains; preload",
            ],
            "response" => [
                "access_token" => "access_token",
                "refresh_token" => "refresh_token",
                "token_type" => "bearer",
                "expires_in" => 3600,
            ],
        ], $merge);
    }

    public static function refreshTokenError(array $merge = []): array
    {
        return array_merge([
            "info" => [
                "url" => "https://api.amazon.com/auth/o2/token",
                "content_type" => "application/json;charset=UTF-8",
                "http_code" => 401,
                "header_size" => 590,
                "request_size" => 892,
                "filetime" => -1,
                "ssl_verify_result" => 0,
                "redirect_count" => 0,
                "total_time" => 0.260245,
                "namelookup_time" => 0.005218,
                "connect_time" => 0.081091,
                "pretransfer_time" => 0.168326,
                "size_upload" => 613,
                "size_download" => 77,
                "speed_download" => 296,
                "speed_upload" => 2357,
                "download_content_length" => 77,
                "upload_content_length" => 613,
                "starttransfer_time" => 0.260186,
                "redirect_time" => 0,
                "redirect_url" => "",
                "primary_ip" => "98.82.161.183",
                "certinfo" => [],
                "primary_port" => 443,
                "local_ip" => "172.20.0.2",
                "local_port" => 56536,
            ],
            "error" => "",
            "headers" => [
                "Server" => "Server",
                "Date" => "Thu, 13 Feb 2025 19:44:09 GMT",
                "Content-Type" => "application/json;charset=UTF-8",
                "Content-Length" => "77",
                "Connection" => "keep-alive",
                "X-Amz-Rid" => "VC93S3D862F77KTZ07ME",
                "X-Amzn-Requestid" => "97521dbc-d398-422f-b013-8e19ddbcc0fd",
                "X-Amz-Date" => "Thu, 13 Feb 2025 19:44:09 GMT",
                "X-Amzn-Errortype" => "OA2InvalidClientException:http://internal.amazon.com/coral/com.amazon.panda/",
                "Cache-Control" => "no-cache, no-store, must-revalidate",
                "Pragma" => "no-cache",
                "Vary" => "Content-Type,Accept-Encoding,User-Agent",
                "Strict-Transport-Security" => "max-age=47474747; includeSubDomains; preload",
            ],
            "response" => [
                "error_description" => "Client authentication failed",
                "error" => "invalid_client",
            ],
        ], $merge);
    }

    public static function clientCredentialsOk(array $merge = []): array
    {
        return array_merge([
            "info" => [
                "url" => "https://api.amazon.com/auth/o2/token",
                "content_type" => "application/json;charset=UTF-8",
                "http_code" => 200,
                "header_size" => 485,
                "request_size" => 597,
                "filetime" => -1,
                "ssl_verify_result" => 0,
                "redirect_count" => 0,
                "total_time" => 0.373178,
                "namelookup_time" => 0.083798,
                "connect_time" => 0.165167,
                "pretransfer_time" => 0.25416,
                "size_upload" => 318,
                "size_download" => 476,
                "speed_download" => 1276,
                "speed_upload" => 852,
                "download_content_length" => 476,
                "upload_content_length" => 318,
                "starttransfer_time" => 0.373113,
                "redirect_time" => 0,
                "redirect_url" => "",
                "primary_ip" => "98.82.161.129",
                "certinfo" => [],
                "primary_port" => 443,
                "local_ip" => "172.20.0.2",
                "local_port" => 48978,
            ],
            "error" => "",
            "headers" => [
                "Server" => "Server",
                "Date" => "Thu, 13 Feb 2025 20:05:48 GMT",
                "Content-Type" => "application/json;charset=UTF-8",
                "Content-Length" => "476",
                "Connection" => "keep-alive",
                "X-Amz-Rid" => "NT6W2QY386RMTZVK40TM",
                "X-Amzn-Requestid" => "be320777-af82-4236-a038-bd64900c70ed",
                "X-Amz-Date" => "Thu, 13 Feb 2025 20:05:48 GMT",
                "Cache-Control" => "no-cache, no-store, must-revalidate",
                "Pragma" => "no-cache",
                "Vary" => "Content-Type,Accept-Encoding,User-Agent",
                "Strict-Transport-Security" => "max-age=47474747; includeSubDomains; preload",
            ],
            "response" => [
                "access_token" => "access_token",
                "scope" => "sellingpartnerapi::notifications",
                "token_type" => "bearer",
                "expires_in" => 3600,
            ],
        ], $merge);
    }

    public static function clientCredentialsError(array $merge = []): array
    {
        return array_merge([
            "info" => [
                "url" => "https://api.amazon.com/auth/o2/token",
                "content_type" => "application/json;charset=UTF-8",
                "http_code" => 401,
                "header_size" => 590,
                "request_size" => 889,
                "filetime" => -1,
                "ssl_verify_result" => 0,
                "redirect_count" => 0,
                "total_time" => 0.338655,
                "namelookup_time" => 0.08153,
                "connect_time" => 0.157663,
                "pretransfer_time" => 0.243823,
                "size_upload" => 610,
                "size_download" => 77,
                "speed_download" => 227,
                "speed_upload" => 1804,
                "download_content_length" => 77,
                "upload_content_length" => 610,
                "starttransfer_time" => 0.338599,
                "redirect_time" => 0,
                "redirect_url" => "",
                "primary_ip" => "98.82.158.136",
                "certinfo" => [],
                "primary_port" => 443,
                "local_ip" => "172.20.0.2",
                "local_port" => 54422,
            ],
            "error" => "",
            "headers" => [
                "Server" => "Server",
                "Date" => "Thu, 13 Feb 2025 20:01:54 GMT",
                "Content-Type" => "application/json;charset=UTF-8",
                "Content-Length" => "77",
                "Connection" => "keep-alive",
                "X-Amz-Rid" => "6HH3NQS3QPKGQTQYFMJF",
                "X-Amzn-Requestid" => "9b617658-d7c5-4897-ab25-fae972afc421",
                "X-Amz-Date" => "Thu, 13 Feb 2025 20:01:54 GMT",
                "X-Amzn-Errortype" => "OA2InvalidClientException:http://internal.amazon.com/coral/com.amazon.panda/",
                "Cache-Control" => "no-cache, no-store, must-revalidate",
                "Pragma" => "no-cache",
                "Vary" => "Content-Type,Accept-Encoding,User-Agent",
                "Strict-Transport-Security" => "max-age=47474747; includeSubDomains; preload",
            ],
            "response" => [
                "error_description" => "Client authentication failed",
                "error" => "invalid_client",
            ],
        ], $merge);
    }
}