name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: release_notes
        run: |
          # Get the previous tag
          prev_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$prev_tag" ]; then
            # If no previous tag exists, get all commits
            git log --pretty=format:"* %s by @%an in %H" > RELEASE_NOTES.md
          else
            # Get commits between previous tag and current
            git log --pretty=format:"* %s by @%an in %H" ${prev_tag}..HEAD > RELEASE_NOTES.md
          fi
          
          # Set output for use in release step
          echo "notes=$(cat RELEASE_NOTES.md)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md