name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: release_notes
        run: |
          release_notes=$(gh pr list \
            --base main \
            --state merged \
            --json title,number,author \
            --search "merged:>=$(git log -1 --format=%aI ${{ env.LATEST_TAG }})" | \
            jq -r '.[] | "- \(.title) by @\(.author.login) in #\(.number)"' | sort)

          echo "notes=$(cat RELEASE_NOTES.md)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md